Complited!!! Точно
MerzL04/Reimer-Konstantin-414 pull request #4
Opened 2022-10-06 07:21 UTC by MerzL04

2022-10-06 07:33 UTC, dmitrii-kruglov requested changes
Нужно придумать чтобы код работал не только со строками из примеров, но и любыми вообще.

2022-10-06 07:34 UTC, dmitrii-kruglov commented
Вы можете изменять файл в ветке и pull request будет изменять автоматически. Не требуется создавать новый после каждых изменений.

2022-10-06 07:39 UTC, MerzL04 commented
Я новый создавал, так как постоянно закрывал новый

2022-10-07 06:48 UTC, MerzL04 commented
Я переделал домашнее задание. Проверьте пожалуйста

2022-10-07 07:23 UTC, dmitrii-kruglov requested changes
Осталось переделать только задачу с кавычками. Все остальное по вашему желанию

2022-10-07 07:23 UTC, dmitrii-kruglov commented on main.py
>  for i in range(len(x)):
Тут можно было просто вывести результат len

2022-10-07 07:23 UTC, dmitrii-kruglov commented on main.py
>  print(z[7:12])
Это работает только с вашей строкой. Нужно придумать решение для любой

2022-10-07 07:23 UTC, dmitrii-kruglov commented on main.py
> +e = int(input("Введите первое число:"))
Без преобразования в int сможете сделать?

2022-10-07 07:23 UTC, dmitrii-kruglov commented on main.py
> +print(b.split("@"))
У вас выведется и логин, и сервер. Требуется только логин

2022-10-07 07:23 UTC, dmitrii-kruglov commented on main.py
> +for word in input().split():
Сможете сделать без цикла?

2022-10-07 09:47 UTC, MerzL04 commented on main.py
>  for i in range(len(x)):
Переделал

2022-10-07 09:47 UTC, MerzL04 commented on main.py
>  print(z[7:12])
Попробую, но не знаю как это сделать

2022-10-07 09:47 UTC, MerzL04 commented on main.py
> +e = int(input("Введите первое число:"))
Сделал

2022-10-07 09:51 UTC, MerzL04 commented on main.py
> +for word in input().split():
У меня не получается без цикла
Выводит:
['Hello', 'world!']

2022-10-07 10:00 UTC, MerzL04 commented on main.py
> +for word in input().split():
Сделал

2022-10-07 10:01 UTC, dmitrii-kruglov commented on main.py
> +for word in input().split():
Если хотите без цикла, то там конечно же нужно использовать другие функции

2022-10-07 10:03 UTC, MerzL04 commented on main.py
> +print(b.split("@"))
Сделал

2022-10-07 10:10 UTC, dmitrii-kruglov requested changes
Решение про задачу с кавычками так и не изменено

2022-10-07 10:10 UTC, dmitrii-kruglov commented on main.py
>  print(z[7:12])
Вот это обязательно нужно переделать

2022-10-07 11:23 UTC, dmitrii-kruglov approved these changes
Теперь могу полностью засчитать задание

2022-10-07 11:23 UTC, dmitrii-kruglov commented on main.py
> +print(z[z.index("'")+1:z.rindex("'")])
Ура!

2022-10-08 06:36 UTC, merged

2022-10-09 11:01 UTC, dmitrii-kruglov reviewed
Решение принято.
Баллы - 3

2022-10-09 11:01 UTC, dmitrii-kruglov commented on dz 2.py
> +    print('TRUE')
Можно же было просто вывести результат операции сравнения без использования ветвления

2022-10-09 11:01 UTC, dmitrii-kruglov commented on dz 2.py
> +    else:
Этот else можно не прописывать